
["VaultMapper Client Config"]
	#Enable rendering the map
	MAP_ENABLED = true
	#Offset the Map from the default position (bottom right) on the x-axis
	MAP_X_OFFSET = 0
	#Offset the Map from the default position (bottom right) on the y-axis
	Map_Y_OFFSET = 0
	#Anchor the Map on the x-axis (0-left, 2-center, 4-right)
	MAP_X_ANCHOR = 4
	#Anchor the Map on the y-axis (0-top, 2-center, 4-bottom)
	MAP_Y_ANCHOR = 2
	#Scale of the map, 3 to 30
	MAP_SCALE = 10
	#Color for the current player position
	POINTER_COLOR = "#00FF00"
	#Color for normal Rooms & Hallways
	ROOM_COLOR = "#0000FF"
	#Color for the Start room of a Vault
	START_ROOM_COLOR = "#FF0000"
	#Color for a Marked Vault Room
	MARKED_ROOM_COLOR = "#FF00FF"
	#Color for a Inscripted Vault Room
	INSCRIPTION_ROOM_COLOR = "#FFFF00"
	#Color for an explored Omega Room
	OMEGA_ROOM_COLOR = "#55FF55"
	#Color for an explored Challenge Room
	CHALLENGE_ROOM_COLOR = "#F09E00"
	#Show Inscripted Rooms on the Map
	SHOW_INSCRIPTIONS = true
	#Show Room Icons on the Map
	SHOW_ROOM_ICONS = true
	#Enable the WebMap Server
	WEBMAP_ENABLED = false
	#The maximum amount of map history snapshots that can be saved on file.
	#Favorites will be saved forever regardless of this number.
	#This number is a global number, not per world/server.
	#Inputting a negative number disables the cap
	MAX_MAPS_SAVED = -1
	#Option to ignore the Vault Compass research requirement for Vault Map.
	#Please don't abuse this option on servers where you don't have permission to do so.
	IGNORE_RESEARCH_REQUIREMENT = false

