name = "Wold's Vaults"
author = "iwolfking"
version = "0.16.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a142a43b66b3b6e82663ba40ae2e0e20a113bcca422107ffbafc6ff03954058"

[versions]
forge = "40.2.13"
minecraft = "1.18.2"
