
#Server configuration settings.
[server]
	#The discord bots token.
	token = "MTA0ODQxOTM5NjQ1ODEyNzQwMA.GSoesH.-VqWFJ9y88w8VBKPOnr3E8mECEzbawIKEb2fKY"
	#The bots activity type.
	#Allowed Values: DISABLED, LISTENING, PLAYING, WATCHING, COMPETING, STREAMING
	activityType = "STREAMING"
	#The streaming URL if activity type is set to streaming.
	streamingURL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

	#Chat Formatting Settings
	[server.chat]
		#The server_chat channel.
		channel = "1211476073162743868"
		#Whether minecraft players can ping @everyone in their chat messages.
		ping_everyone = false
		#Whether the deaths of named entities should be posted in server chat. Disable if there are mods that spawn entities with custom names.
		postEntityDeaths = false
		#The command that can be run in the server chat channel to list all online players.
		listPlayerCommand = "/list"
		#List of bot id's whos messages will be transmitted to minecraft chat when a message is sent in the server chat channel.
		botWhitelist = []

	#Console Bot Settings
	[server.console]
		#The console channel.
		#IMPORTANT NOTE: This channel allows any discord user to run admin commands without prejudice, so make sure that this channel is only accessible by those you trust.
		channel = "000000000000000000"
		#The prefix required to execute console commands.
		#Leave empty to have all text inputs be processed as a command.
		prefix = "/"

	#Account linking settings.
	[server.account]
		#The role given to members that are allowed to run the 'linkuser' & 'unlinkplayer' command.
		adminRoles = ["000000000000000000"]
		#Whether a user should also be whitelisted when linked by the 'linkuser' command.
		autoWhitelist = false
		#Prefix for the account related commands.
		prefix = "!"
		#List of channel id's that the account bot should ignore commands from.
		#Note: Channels used by other listeners will be automatically ignored.
		channelBlacklist = []

