
[general]
	milk = true
	#Range: > 1
	gauntlet_cooldown = 600
	coat_tools = true
	spike_food = true
	coat_anything = true
	show_spiked_food = true
	#Cooldown in ticks when switching to potions
	#Range: 0 ~ 20000
	potion_switch_cooldown = 30
	#Cooldown in ticks when throwing potions
	#Range: 0 ~ 20000
	potion_throw_cooldown = 30
	#Allows all items to be coated
	coat_all = true
	#Number of uses per coating
	#Range: > 1
	coating_uses = 100
	#Range: 1 ~ 64
	potion_stack_size = 16
	#Range: 1 ~ 64
	splash_potion_stack_size = 4
	#Range: 1 ~ 64
	lingering_potion_stack_size = 4

