
#Client Configuration
[client]

	[client.options]
		# If the hotbar should display item borders.
		hotbar = false
		# If item borders should show for common items.
		show_for_common = false
		# If the borders should have square corners.
		square_corners = true
		# If the borders should fully envelop item slots (otherwise they will only show on the bottom portion of the slot).
		full_border = false
		# If the borders draw over items instead of under.
		over_items = true
		# If the borders should have a more prominent glow.
		extra_glow = true
		# If automatic borders (based on item rarity) should be enabled.
		auto_borders = true

		# Custom border colors for specific items. Format: { <color> = ["list of selectors"] }. Selectors supported:
		#    Item name - Use item name for vanilla items or include mod name for modded items.  Examples: minecraft:stick, iron_ore
		#    Tag - $ followed by tag name.  Examples: $forge:stone or $planks
		#    Mod name - @ followed by mod identifier.  Examples: @spoiledeggs
		#    Rarity - ! followed by item's rarity.  This is ONLY vanilla rarities.  Examples: !uncommon, !rare, !epic
		#    Item name color - # followed by color hex code, the hex code must match exactly.  Examples: #23F632
		#    Display name - % followed by any text.  Will match any item with this text in its tooltip display name.  Examples: %[Uncommon]
		#    Tooltip text - ^ followed by any text.  Will match any item with this text anywhere in the tooltip text (besides the name).  Examples: ^Rarity: Legendary
		[client.options.manual_borders]
			FFA800 = ["the_vault:unidentified_artifact", "the_vault:vault_artifact"]
			F4358F = ["the_vault:trinket"]
			8BFFCA = ["the_vault:inscription"]
			BCBCBC = ["^Rarity: Scrappy"]
			51AEFF = ["^Rarity: Common"]
			FFE800 = ["^Rarity: Rare", "woldsvaults:general_decor_scroll"]
			FF00FF = ["^Rarity: Epic", "woldsvaults:expertise_orb", "woldsvaults:capstone_all_seeing_eye"]
			6AFF00 = ["^Rarity: Omega", "woldsvaults:omega_box"]
			DF80FF = ["the_vault:wold_star", "the_vault:wold_star_chunk"]

