
#QOLHunters Configuration
#SOME CHANGES REQUIRE A CLIENT RESTART
["General Configs"]
	#Disables QOL mods that cannot work on vanilla VH servers (disables all mods in the 'Client-Server Extensions' list)
	#Be very careful if you change this on single player worlds! For example, if you have emeralds in your enchantment table and you enable this, those will probably get deleted if you load the world before changing this back
	#Requires Restart
	"Vanilla Safe Mode" = false
	#Show the Config Button in the Statistics Menu (H)
	"Show Config Button" = true

["Client-Only Extensions"]
	#Adds text overlays to the Vault modifiers, e.g. '+10% Damage' or 'Speed +1'
	"Vault Modifier Text Overlays" = false
	#Adds keybinds to craft/forge/reroll in the Bounty Table, Enchanter, Vault Forge, etc
	"Vault Interface Keybinds" = true
	#Improves the Abilities Tab including levelling specializations directly and showing all possible levels/overlevels
	"Better Abilities Tab" = true
	#Saves and loads current keybinds when you save/load skills in the Skill Altar
	"Skill Altar Save Keybinds" = true
	#Render a timer over Vault Gear items that are on cooldown
	"Show Gear Cooldown Time" = true
	#Allows you to cast multiple abilities with a single keybind
	"Ability Multicast" = true
	#Automatically open the next booster pack in your inventory after you select a card
	"Chain Booster Packs" = true
	#Show treasure door names in the vault
	"Treasure Door Names" = true
	#Add inventory buttons / use arrow keys to cycle through backpacks in your inventory
	"Backpack Cycler" = false
	#Autoswap to the correct treasure key when you right-click a treasure door with another key as long as the correct key is in your main inventory
	"Treasure Key Swapper" = false

	["Client-Only Extensions"."Better Descriptions"]
		#Improves descriptions in the 'Statistics' Tab.
		"Better Stats Descriptions" = false
		#Improves descriptions in the 'Abilities' Tab.
		#Disable if you're not on version 3.15.1.4
		"Better Abilities Descriptions" = false
		#Improves descriptions in the 'Talents', 'Expertises', and 'Researches' Tabs.
		#Disable if you're not on version 3.15.1.4
		"Better Talents, Expertise, Research Descriptions" = false

		["Client-Only Extensions"."Better Descriptions"."Better Soul Value Tooltips"]
			#Improves the descriptions of soul values in tooltips when holding SHIFT
			"Enable Better Tooltips" = true
			#Uses shorthand for soul values in tooltips (e.g. 1.4M instead of 1408933)
			"Use Shorthand" = true
			#Use soul shards instead of soul value 
			"Use Soul Shards" = false

	["Client-Only Extensions"."Black Market"]
		#Displays the number of shards in your Shard Pouch within the Black Market's interface
		"Black Market Shard Pouch Count" = false
		#Uses shorthand for the Black Market Shard Pouch count (e.g. 1.4M instead of 1408933)
		"Black Market Shard Pouch Count Shorthand" = false

	["Client-Only Extensions"."Scavenger Vaults"]
		#Shows the number of scavenger items you have in your inventory
		"Scavenger Inventory Count" = true
		#Highlights current objective scavenger items in your inventory
		"Scavenger Highlighter" = true

	["Client-Only Extensions"."Brazier Vaults"]
		#Changes the mode of the Brazier Hologram
		#DEFAULT = Always show all icons and text
		#MODE1 = Always show icons, text renders when close to the brazier
		#MODE2 = Always show icons, hold SHIFT to show text
		#MODE3 = Always show icons and labels, hold SHIFT to show descriptions
		#Allowed Values: DEFAULT, MODE1, MODE2, MODE3
		"Brazier Hologram Mode" = "DEFAULT"

	["Client-Only Extensions"."Cake Vaults"]
		#Changes the color of the Vault Cake overlay
		#Allowed Values: PINK, BLUE, YELLOW, GREEN
		"Cake Vault Overlay Color" = "PINK"
		#Changes the style of the Vault Cake overlay
		#Allowed Values: VIGNETTE, RADAR
		"Cake Vault Overlay Style" = "VIGNETTE"

	["Client-Only Extensions"."Bingo Vaults"]
		#Changes the opacity (%) of the Bingo Grid background
		#Range: 0 ~ 100
		"Grid Background Opacity" = 50
		#Improves the descriptions of bingo objectives in Bingo Vaults
		#Might not work on servers?
		"Better Bingo Descriptions" = false
		#Changes the color of the Bingo Grid completion overlay
		#Allowed Values: RED, BLUE, YELLOW, GREEN, GLORP
		"Grid Completion Color" = "GREEN"
		#Changes the color of the Bingo Grid selection overlay
		#Allowed Values: RED, BLUE, YELLOW, GREEN, GLORP
		"Grid Selection Color" = "YELLOW"

	["Client-Only Extensions"."HUD Positioning"]

		["Client-Only Extensions"."HUD Positioning"."God Objective"]
			#Changes the X offset of the God Objective
			#Defined as % of screen width
			#Range: 0 ~ 100
			"God Objective X Offset" = 0
			#Changes the Y offset of the God Objective
			#Defined as % of screen height
			#Range: 0 ~ 100
			"God Objective Y Offset" = 45

		["Client-Only Extensions"."HUD Positioning"."Vault Modifiers"]
			#Render Vault Modifiers in the top right corner of the screen
			"Vault Modifiers In Top Right" = false

	["Client-Only Extensions"."Paradox Vaults"]
		#Hold <SHIFT> to enlarge the paradox vault gate unlock text.
		#Note: Designed for BUILD mode, but currently also takes effect when running the vault too.
		"Paradox Gate Zoom" = false

	["Client-Only Extensions"."Shopping Pedestals"]
		#Includes your bartering discount on shopping pedestals
		"Enable Bartering Discount Display" = true
		#Shopping pedestals throw items so that your magnets/bags can pick them up instead
		"Shopping Pedestal Throws Items" = false

	["Client-Only Extensions"."Rarity Highlighter"]
		#Enable highlighting Vault Gear in your Inventory while holding <SHIFT>
		"Enable Rarity Highlighter" = false
		#Highlighter Mode
		#Allowed Values: GRADIENT, UNDERLINE
		"Highlighter Mode" = "GRADIENT"
		#Highlight Rare Gear
		"Highlight Rare Gear" = true
		#Highlight Epic Gear
		"Highlight Epic Gear" = true
		#Highlight Omega Gear
		"Highlight Omega Gear" = true
		#Highlight Unique Gear
		"Highlight Unique Gear" = true

	#Use a Warped Fungus on a Stick to configure Virtual Dehammerizer.
	#Use arrow UP/DOWN keys to cycle between Dehammerizers.
	#Use Ctrl+RightClick to add a Dehammerizer.
	#Use Ctrl+Delete to remove a Dehammerizer
	["Client-Only Extensions"."Virtual Dehammerizer"]
		#Enable Virtual Dehammerizer
		"Enable Virtual Dehammerizer" = true
		#Virtual Dehammerizer Mode
		#Choose SPHERE for a sphere defined around the chosen block position.
		#Choose CYLINDER to encompass the full height of the map
		#Allowed Values: SPHERE, CYLINDER
		"Dehammerizer Mode" = "SPHERE"
		#Virtual Dehammerizer Range
		#Range: 8 ~ 64
		"Dehammerizer Range" = 24

	["Client-Only Extensions"."Hunter Particles"]
		#Show Hunter Particles for Objectives/Altars
		Objectives = true
		#Show Hunter Particles for Gilded Chests
		Gilded = true
		#Show Hunter Particles for Living Chests
		Living = true
		#Show Hunter Particles for Ornate Chests
		Ornate = true
		#Show Hunter Particles for Coins
		Coins = true
		#Show Hunter Particles for Wooden Chests
		Wooden = true
		#Show Default White Hunter Particles
		Default = true

["Client-Server Extensions"]
	#Adds an emerald slot to the Vault Enchanter
	#This setting will be safely ignored if you connect to a server without QOLHunters installed
	"Vault Enchanter Emeralds Slot" = true

